version: "3.5"

networks:
    inception: {}

services:

#---------------------NGINX------------------------#
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        image: nginx
        networks:
            - inception
        ports:
            - 443:443
        depends_on:
            - wordpress
            - mariadb
        restart: always
        volumes:
            - nginx_data:/var/log/nginx
            - wordpress_data:/var/www/wordpress


#-------------------WORDPRESS---------------------#
    wordpress:
        container_name: wordpress
        image: wordpress
        build: 
            context: ./requirements/wordpress
        env_file:
            - .env
        networks:
            - inception
        depends_on:
            - mariadb
        restart: always
        volumes:
            - wordpress_data:/var/www/wordpress


#-------------------MARIADB---------------------#
    mariadb:
        container_name: mariadb
        image: mariadb
        build: 
            context: ./requirements/mariadb
        networks:
            - inception
        volumes:
            - mariadb_data:/var/lib/mysql
        env_file:
            - .env
        restart: always

volumes:
    mariadb_data:
        driver_opts:
            type: "none"
            o: "bind"
            device: "/home/tpauvret/data/mariadb"

    wordpress_data:
        driver_opts:
            type: "none"
            o: "bind"
            device: "/home/tpauvret/data/wordpress"

    nginx_data:
        driver_opts:
            type: "none"
            o: "bind"
            device: "/home/tpauvret/data/nginx"

