version: "3.3"

networks:
        inception: {}

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        networks:
            - inception
        ports:
            - "443:443"
        depends_on:
            - wordpress
            - mariadb
        restart: always

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        networks:
            - inception
        depends_on:
            - mariadb
        restart: always

    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        networks:
            - inception
        restart: always
